### ISSUE TITLE
Import error of sarra_py in the notebook

### ISSUE THREAD

**Issue by remydecoupes** [SARRA-cropmodels/SARRA-Py#2]
The import box from [notebook](https://github.com/SARRA-cropmodels/SARRA-Py/blob/dev/notebooks/SARRA-Py_grid.ipynb) stops when importing sarra_py:

```python
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 10
      8 import io
      9 import xarray as xr
---> 10 from sarra_py import *
     11 import time

ModuleNotFoundError: No module named 'sarra_py'
```

**Comment by codename5281** [comment]
Hello @remydecoupes, thanks for your feedback.

By following the installation instructions from the [README](https://github.com/SARRA-cropmodels/SARRA-Py/blob/bb52d53c24b5e8564248bde676a331d563ebeffd/README.md) file, and passing a `git checkout dev` before installing the package via `pip install .` (as the current code isn't in the `main` branch yet) i wasn't able to replicate this issue.

Could you provide more information about how you did it ?

**Comment by remydecoupes** [comment]
You're right, I forgot to mention it.

I was working on the dev branch and my development environment was as I described in the pull request #1:

- a conda environment
- with jupyterlab launched from this environment

I'm going to re-test it. I'll let you know.

**Comment by codename5281** [comment]
I just tested it by using the conda development environment setup you suggested in your pull request [#1](https://github.com/SARRA-cropmodels/SARRA-Py/pull/1) - now merged, except that i use the VScode Jupyter instance instead of the suggested jupyterlab install. By running the VScode Jupyter instance's IPython kernel on the `sarra_py` conda environment suggested in the updated [README](https://github.com/SARRA-cropmodels/SARRA-Py/blob/57000cc940580f006e087ff223a54925ef4d3c5f/README.md), i don't have any import issue.

**Comment by remydecoupes** [comment]
I have just tried to import sarra_py and I still have the same import error.

When I list the packages installed in my conda env, I don't see any package related to sarra_py:

```bash
(sarra_py) user$ conda list |grep sarra
# packages in environment at mambaforge/envs/sarra_py:
```

I was able to import it by adding those 2 lines in the import box:
```python
import sys
sys.path.append('./../src/')
```

**Comment by remydecoupes** [comment]
Sorry, I didn't follow the readme instructions. I run `pip install -r requirements.txt` instead of `pip install .` 
Now I see sarra-py in my conda env and I can import it.
